Repository aws-controllers-k8s/prometheusservice-controller, pull requests merged in 2022-09, with the labels that each got.

#16 Release artifacts for release v0.1.0
  config/controller/kustomization.yaml
  helm/Chart.yaml
  helm/templates/NOTES.txt
  helm/templates/deployment.yaml
  helm/values.yaml
Labels: approved

#14 remove dev preview from olm file in preparation for GA
  olm/olmconfig.yaml
Labels: lgtm, approved, needs-ok-to-test

#18 Update to ACK runtime `v0.20.1`, code-generator `v0.20.1`
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/enums.go
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/prometheusservice.services.k8s.aws_alertmanagerdefinitions.yaml
  config/crd/bases/prometheusservice.services.k8s.aws_rulegroupsnamespaces.yaml
  config/crd/bases/prometheusservice.services.k8s.aws_workspaces.yaml
  config/rbac/cluster-role-controller.yaml
  generator.yaml
  go.mod
  go.sum
  helm/crds/prometheusservice.services.k8s.aws_alertmanagerdefinitions.yaml
  helm/crds/prometheusservice.services.k8s.aws_rulegroupsnamespaces.yaml
  helm/crds/prometheusservice.services.k8s.aws_workspaces.yaml
  helm/crds/services.k8s.aws_adoptedresources.yaml
  helm/crds/services.k8s.aws_fieldexports.yaml
Labels: lgtm, approved
